export const MATCH_STATUS = {
  IS_IT_ME_SEND: 'IS_IT_ME_SEND',
  IS_IT_ME_RECEIVE: 'IS_IT_ME_RECEIVE',
  POST_LABEL_SEND: 'POST_LABEL_SEND',
  POST_LABEL_RECEIVE: 'POST_LABEL_RECEIVE',
  WRONG_SEND: 'WRONG_SEND',
  WRONG_RECEIVE: 'WRONG_RECEIVE',
  NAME_SEND: 'NAME_SEND',
  NAME_RECEIVE: 'NAME_RECEIVE',
  REJECT_SEND: 'REJECT_SEND',
  REJECT_RECEIVE: 'REJECT_RECEIVE',
  ANSWER_SEND: 'ANSWER_SEND',
  ANSWER_RECEIVE: 'ANSWER_RECEIVE',
};

export const ANSWER = {
  NO: 'NO',
  YES: 'YES',
};

export const WHERE = {
  ALARM: 'ALARM',
  BOAT: 'BOAT',
  SERVICE: 'SERVICE',
  MATCH_LOG: 'MATCH_LOG',
  TOKEN_GUARD: 'TOKEN_GUARD',
};

export const WHERE_LOG = {
  ALARM: '🛎 ALARM 🛎',
  BOAT: '⛵ BOAT ⛵',
  SERVICE: '🎱 SERVICE 🎱',
  MATCH_LOG: '🧩 MATCH_LOG 🧩',
  TOKEN_GUARD: '🛡 TOKEN_GUARD 🛡',
};
