import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/common/header';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body
                className={
                    'relative w-screen h-screen flex flex-col items-center bg-gray-200'
                }
            >
                <Header />
                <div
                    className={
                        'max-w-380 h-full bg-white overflow-y-auto overflow-x-hidden'
                    }
                >
                    {children}
                </div>
            </body>
        </html>
    );
}
